### ISSUE TITLE
Searching is not region-wide

### ISSUE THREAD

**Issue by ualch9** [OneBusAway/OBAKit#403]
## Reproduction
In Puget Sound,
1. Scroll map to Marysville
2. Search for route "10"
3. No search results found

## Expected Behavior
1. Scroll map to Marysville
2. Search for route "10"
3. Two search results, "10 - Metro Transit" and "10 - Pierce Transit"

**Comment by aaronbrethorst** [comment]
This was an intentional design choice. I'm amenable to revisiting it, but it's not a bug.

**Comment by barbeau** [comment]
FWIW, due to user complaints on Android over time we expanded to have a default search radius of 40,000 meters:
https://github.com/OneBusAway/onebusaway-android/blob/6cd597042d61fe262888b0d8b8e4ed3ede6ecaf9/onebusaway-android/src/main/java/org/onebusaway/android/util/LocationUtils.java#L59

Users said it was confusing to get an empty result set when searching far away from a route/stop when they know it exists.

**Comment by aaronbrethorst** [comment]
We’re at 40,000 meters too.
